### ISSUE TITLE
Import TikiSdk in iOS TikiSdk Capacitor is not working

### ISSUE THREAD

**Issue by ricardobrg** [tiki/tiki-sdk-capacitor#68]
The TIKI SDK is added to TIKI SDK Capactior iOS as a native import through Swift Package Manager in Xcode Workspace.

![Image](https://user-images.githubusercontent.com/8357343/265467001-aaead318-76a9-4345-9120-98f5b700f8c8.png)

In the example project for Tiki Sdk Capacitor in iOS, it cannot be found

![Image](https://user-images.githubusercontent.com/8357343/265467352-70acecec-8c4c-4488-b49f-93600975d4e5.png)

The recomendation from Capacitor is to [add all the dependencies in the podspec file](https://capacitorjs.com/docs/plugins/ios#:~:text=Capacitor%20iOS%20plugins%20are%20CocoaPods,to%20see%20all%20possible%20options.). But currently it is not possible to add a SPM dependency in a podspec file, [until they finally merge this PR](https://github.com/CocoaPods/CocoaPods/pull/11953#issuecomment-1701737145).

We have 2 possibilities to fix this:

1 - manually link the TikiSdk in the workspace file for TikiSdk Capacitor
2 - create a custom build for TikiSdk Capacitor that includes the TikiSdk dependency

**Comment by JesseMonteiro** [comment]
We had to change the capacitor and cordova pods dependencies to SPM to we had the scope of the package dependencies of packages and we need to made a package of the tiki-sdk-capacitor to integrate with plugin.
